# Generated by Django 4.2.24 on 2025-10-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertasistema',
            name='tipo',
            field=models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('error', 'Error'), ('success', 'Éxito')], default='info', max_length=20),
        ),
    ]
