# Generated by Django 4.2.24 on 2025-09-05 18:21

import apps.core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioVacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre_vacuna', models.CharField(max_length=100, verbose_name='Nombre de la Vacuna')),
                ('dias_post_nacimiento', models.PositiveIntegerField(verbose_name='Días Post-Nacimiento')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('dosis_ml', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Dosis (ml)')),
                ('via_aplicacion', models.CharField(max_length=50, verbose_name='Vía de Aplicación')),
                ('obligatoria', models.BooleanField(default=True, verbose_name='Obligatoria')),
            ],
            options={
                'verbose_name': 'Calendario de Vacunas',
                'verbose_name_plural': 'Calendario de Vacunas',
                'ordering': ['dias_post_nacimiento'],
            },
        ),
        migrations.CreateModel(
            name='LoteAves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre_lote', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Lote')),
                ('linea', models.CharField(choices=[('babcock_brown', 'Babcock Brown'), ('hy_line_brown', 'Hy-Line Brown'), ('lohmann_brown', 'Lohmann Brown'), ('isa_brown', 'ISA Brown'), ('bovans_brown', 'Bovans Brown'), ('otra', 'Otra')], max_length=20, verbose_name='Línea Genética')),
                ('fecha_inicio', models.DateField(validators=[apps.core.utils.validar_fecha_no_futura], verbose_name='Fecha de Inicio')),
                ('cantidad_aves', models.PositiveIntegerField(verbose_name='Cantidad de Aves Inicial')),
                ('cantidad_actual', models.PositiveIntegerField(verbose_name='Cantidad Actual de Aves')),
                ('semana_actual', models.PositiveIntegerField(default=1, verbose_name='Semana de Producción')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('vendido', 'Vendido')], default='activo', max_length=15, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Lote de Aves',
                'verbose_name_plural': 'Lotes de Aves',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_programada', models.DateField(verbose_name='Fecha Programada')),
                ('fecha_aplicacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Aplicación')),
                ('dosis_aplicada', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Dosis Aplicada (ml)')),
                ('numero_aves_vacunadas', models.PositiveIntegerField(verbose_name='Número de Aves Vacunadas')),
                ('responsable', models.CharField(max_length=100, verbose_name='Responsable')),
                ('lote_vacuna', models.CharField(blank=True, max_length=50, verbose_name='Lote de Vacuna')),
                ('estado', models.CharField(choices=[('aplicada', 'Aplicada'), ('pendiente', 'Pendiente'), ('vencida', 'Vencida')], default='pendiente', max_length=10, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('calendario_vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aves.calendariovacunas', verbose_name='Vacuna del Calendario')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunaciones', to='aves.loteaves', verbose_name='Lote')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
            ],
            options={
                'verbose_name': 'Vacunación',
                'verbose_name_plural': 'Vacunaciones',
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='Mortalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha', models.DateField(validators=[apps.core.utils.validar_fecha_no_futura], verbose_name='Fecha')),
                ('cantidad_muertas', models.PositiveIntegerField(verbose_name='Cantidad de Aves Muertas')),
                ('causa', models.CharField(choices=[('enfermedad', 'Enfermedad'), ('accidente', 'Accidente'), ('estres', 'Estrés'), ('depredacion', 'Depredación'), ('vejez', 'Vejez'), ('desconocida', 'Desconocida'), ('otra', 'Otra')], max_length=15, verbose_name='Causa')),
                ('descripcion_causa', models.TextField(blank=True, verbose_name='Descripción de la Causa')),
                ('accion_tomada', models.TextField(blank=True, verbose_name='Acción Tomada')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mortalidades', to='aves.loteaves', verbose_name='Lote')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
            ],
            options={
                'verbose_name': 'Mortalidad',
                'verbose_name_plural': 'Mortalidades',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ProduccionHuevos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha', models.DateField(validators=[apps.core.utils.validar_fecha_no_futura], verbose_name='Fecha de Producción')),
                ('semana_produccion', models.PositiveIntegerField(verbose_name='Semana de Producción')),
                ('yumbos', models.PositiveIntegerField(default=0, verbose_name='Yumbos')),
                ('extra', models.PositiveIntegerField(default=0, verbose_name='Extra')),
                ('aa', models.PositiveIntegerField(default=0, verbose_name='AA')),
                ('a', models.PositiveIntegerField(default=0, verbose_name='A')),
                ('b', models.PositiveIntegerField(default=0, verbose_name='B')),
                ('c', models.PositiveIntegerField(default=0, verbose_name='C')),
                ('pipo', models.PositiveIntegerField(default=0, verbose_name='Pipo')),
                ('sucios', models.PositiveIntegerField(default=0, verbose_name='Sucios')),
                ('totiados', models.PositiveIntegerField(default=0, verbose_name='Totiados')),
                ('yema', models.PositiveIntegerField(default=0, verbose_name='Yema')),
                ('peso_promedio_huevo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso Promedio por Huevo (g)')),
                ('numero_aves_produccion', models.PositiveIntegerField(verbose_name='Número de Aves en Producción')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='aves.loteaves', verbose_name='Lote')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
            ],
            options={
                'verbose_name': 'Producción de Huevos',
                'verbose_name_plural': 'Producción de Huevos',
                'ordering': ['-fecha'],
                'unique_together': {('lote', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='IndicadorProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_calculo', models.DateField(auto_now=True, verbose_name='Fecha de Cálculo')),
                ('semana_produccion', models.PositiveIntegerField(verbose_name='Semana de Producción')),
                ('porcentaje_postura_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Postura Promedio')),
                ('huevos_ave_alojada', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Huevos por Ave Alojada')),
                ('gramos_ave_dia_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Gramos Ave/Día Promedio')),
                ('peso_huevo_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Peso Huevo Promedio (g)')),
                ('costo_por_huevo', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Costo por Huevo')),
                ('ingreso_por_huevo', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Ingreso por Huevo')),
                ('margen_por_huevo', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='Margen por Huevo')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='aves.loteaves', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Indicador de Producción',
                'verbose_name_plural': 'Indicadores de Producción',
                'ordering': ['-fecha_calculo'],
                'unique_together': {('lote', 'semana_produccion')},
            },
        ),
        migrations.CreateModel(
            name='CostosProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha', models.DateField(validators=[apps.core.utils.validar_fecha_no_futura], verbose_name='Fecha')),
                ('periodo', models.CharField(help_text='Ej: Semana 1, Mes 1', max_length=20, verbose_name='Período')),
                ('costos_fijos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costos Fijos')),
                ('costos_variables', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costos Variables')),
                ('gastos_administracion', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gastos de Administración')),
                ('costo_alimento', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo de Alimento')),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo Mano de Obra')),
                ('otros_costos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otros Costos')),
                ('ingresos_venta_huevos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ingresos por Venta de Huevos')),
                ('ingresos_venta_aves', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ingresos por Venta de Aves')),
                ('otros_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Otros Ingresos')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='aves.loteaves', verbose_name='Lote')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
            ],
            options={
                'verbose_name': 'Costos de Producción',
                'verbose_name_plural': 'Costos de Producción',
                'ordering': ['-fecha'],
                'unique_together': {('lote', 'fecha', 'periodo')},
            },
        ),
    ]
