# Generated by Django 4.2.24 on 2025-09-30 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientohuevos',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='movimientohuevos',
            name='categoria_huevo',
        ),
        migrations.RemoveField(
            model_name='movimientohuevos',
            name='precio_unitario',
        ),
        migrations.CreateModel(
            name='DetalleMovimientoHuevos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('categoria_huevo', models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=3, verbose_name='Categoría')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio unitario')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='aves.movimientohuevos', verbose_name='Movimiento')),
            ],
            options={
                'verbose_name': 'Detalle de Movimiento de Huevos',
                'verbose_name_plural': 'Detalles de Movimientos de Huevos',
                'unique_together': {('movimiento', 'categoria_huevo')},
            },
        ),
    ]
