# Generated by Django 4.2.24 on 2025-09-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacoradiaria',
            name='consumo_alimento',
        ),
        migrations.RemoveField(
            model_name='bitacoradiaria',
            name='humedad_max',
        ),
        migrations.RemoveField(
            model_name='bitacoradiaria',
            name='humedad_min',
        ),
        migrations.RemoveField(
            model_name='bitacoradiaria',
            name='temperatura_max',
        ),
        migrations.RemoveField(
            model_name='bitacoradiaria',
            name='temperatura_min',
        ),
        migrations.AddField(
            model_name='bitacoradiaria',
            name='causa_mortalidad',
            field=models.CharField(blank=True, max_length=200, verbose_name='Causa de mortalidad'),
        ),
        migrations.AddField(
            model_name='bitacoradiaria',
            name='consumo_concentrado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Consumo concentrado (kg)'),
        ),
        migrations.AddField(
            model_name='bitacoradiaria',
            name='semana_vida',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Semana de vida'),
        ),
    ]
