# Generated by Django 4.2.24 on 2025-09-09 02:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaSanitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo', models.CharField(choices=[('mortalidad_alta', 'Mortalidad Alta'), ('postura_baja', 'Postura Baja'), ('peso_bajo', 'Peso Promedio Bajo'), ('vacuna_vencida', 'Vacuna Vencida'), ('costo_alto', 'Costo Elevado')], max_length=20)),
                ('mensaje', models.TextField()),
                ('valor_actual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_umbral', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='loteaves',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='loteaves',
            name='costo_ave_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='loteaves',
            name='fecha_fin_produccion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loteaves',
            name='cantidad_actual',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='loteaves',
            name='cantidad_aves',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='loteaves',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vendido', 'Vendido'), ('terminado', 'Terminado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='loteaves',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loteaves',
            name='linea',
            field=models.CharField(choices=[('hy_line_brown', 'Hy-Line Brown'), ('hy_line_white', 'Hy-Line White'), ('lohmann_brown', 'Lohmann Brown'), ('isa_brown', 'ISA Brown'), ('bovans_brown', 'Bovans Brown'), ('otra', 'Otra')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loteaves',
            name='nombre_lote',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='loteaves',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='loteaves',
            name='semana_actual',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='produccionhuevos',
            name='peso_promedio_huevo',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(100)], verbose_name='Peso Promedio por Huevo (g)'),
        ),
        migrations.AddIndex(
            model_name='loteaves',
            index=models.Index(fields=['estado'], name='aves_loteav_estado_3c2ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='loteaves',
            index=models.Index(fields=['linea'], name='aves_loteav_linea_ce2cb7_idx'),
        ),
        migrations.AddIndex(
            model_name='loteaves',
            index=models.Index(fields=['fecha_inicio'], name='aves_loteav_fecha_i_f0510c_idx'),
        ),
        migrations.AddIndex(
            model_name='loteaves',
            index=models.Index(fields=['codigo'], name='aves_loteav_codigo_78668e_idx'),
        ),
        migrations.AddIndex(
            model_name='mortalidad',
            index=models.Index(fields=['lote', 'fecha'], name='aves_mortal_lote_id_2b6694_idx'),
        ),
        migrations.AddIndex(
            model_name='mortalidad',
            index=models.Index(fields=['fecha'], name='aves_mortal_fecha_015804_idx'),
        ),
        migrations.AddIndex(
            model_name='mortalidad',
            index=models.Index(fields=['causa'], name='aves_mortal_causa_cc9794_idx'),
        ),
        migrations.AddIndex(
            model_name='produccionhuevos',
            index=models.Index(fields=['lote', 'fecha'], name='aves_produc_lote_id_566a96_idx'),
        ),
        migrations.AddIndex(
            model_name='produccionhuevos',
            index=models.Index(fields=['fecha'], name='aves_produc_fecha_3f26c8_idx'),
        ),
        migrations.AddIndex(
            model_name='produccionhuevos',
            index=models.Index(fields=['semana_produccion'], name='aves_produc_semana__b1ea38_idx'),
        ),
        migrations.AddIndex(
            model_name='produccionhuevos',
            index=models.Index(fields=['lote', 'semana_produccion'], name='aves_produc_lote_id_bc609f_idx'),
        ),
        migrations.AddField(
            model_name='alertasanitaria',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aves.loteaves'),
        ),
    ]
