# Generated by Django 4.2.24 on 2025-10-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0003_add_stock_automatico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertasistema',
            name='nivel',
            field=models.CharField(choices=[('critica', 'Crítica'), ('normal', 'Normal')], max_length=10, verbose_name='Nivel'),
        ),
    ]
