# Generated by Django 4.2.24 on 2025-10-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0005_add_tipo_field_safe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallemovimientohuevos',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='detallemovimientohuevos',
            name='precio_unitario',
        ),
        migrations.AddField(
            model_name='detallemovimientohuevos',
            name='cantidad_docenas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad en docenas (12 unidades por docena)', max_digits=10, verbose_name='Cantidad (docenas)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallemovimientohuevos',
            name='precio_por_docena',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio por cada docena de huevos', max_digits=10, null=True, verbose_name='Precio por docena'),
        ),
        migrations.AddField(
            model_name='loteaves',
            name='tipo',
            field=models.CharField(choices=[('ponedoras', 'Ponedoras'), ('engorde', 'Engorde')], default='ponedoras', max_length=20, verbose_name='Tipo de lote'),
        ),
    ]
