# Generated by Django 4.2.24 on 2025-10-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0006_cambio_a_docenas'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoradiaria',
            name='huevos_rotos',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad total de huevos rotos en el día', verbose_name='Huevos rotos'),
        ),
        migrations.AddField(
            model_name='bitacoradiaria',
            name='recoleccion_1',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad total de huevos en la primera recolección', verbose_name='Primera recolección'),
        ),
        migrations.AddField(
            model_name='bitacoradiaria',
            name='recoleccion_2',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad total de huevos en la segunda recolección', verbose_name='Segunda recolección'),
        ),
        migrations.AddField(
            model_name='bitacoradiaria',
            name='recoleccion_3',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad total de huevos en la tercera recolección', verbose_name='Tercera recolección'),
        ),
    ]
