# Generated by Django 4.2.26 on 2025-11-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0007_add_recolecciones_huevos_rotos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteaves',
            name='linea_genetica',
            field=models.CharField(choices=[('hy_line_brown', 'Hy-Line Brown'), ('hy_line_white', 'Hy-Line White'), ('lohmann_brown', 'Lohmann Brown'), ('lohmann_white', 'Lohmann White'), ('isa_brown', 'ISA Brown'), ('isa_white', 'ISA White'), ('bovans_brown', 'Bovans Brown'), ('bovans_white', 'Bovans White'), ('dekalb_brown', 'Dekalb Brown'), ('dekalb_white', 'Dekalb White'), ('babcock_brown', 'Babcock Brown'), ('otra', 'Otra')], max_length=50, verbose_name='Línea genética'),
        ),
        migrations.AlterField(
            model_name='movimientohuevos',
            name='tipo_movimiento',
            field=models.CharField(choices=[('venta', 'Venta'), ('autoconsumo', 'Autoconsumo')], max_length=15, verbose_name='Tipo de movimiento'),
        ),
    ]
