# Generated by Django 4.2.25 on 2026-02-13 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aves', '0009_inventarioaves_remove_registromodificacion_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo_alerta', models.CharField(choices=[('stock_bajo', 'Stock Bajo'), ('mortalidad_alta', 'Mortalidad Alta'), ('vacuna_pendiente', 'Vacuna Pendiente'), ('produccion_baja', 'Producción Baja')], max_length=30, verbose_name='Tipo de alerta')),
                ('nivel', models.CharField(choices=[('critica', 'Crítica'), ('normal', 'Normal')], max_length=10, verbose_name='Nivel')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('galpon_nombre', models.CharField(blank=True, max_length=100, verbose_name='Galpón')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aves.loteaves')),
                ('usuario_destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_aves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta del Sistema',
                'verbose_name_plural': 'Alertas del Sistema',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroModificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('objeto_id', models.PositiveIntegerField(verbose_name='ID del objeto')),
                ('accion', models.CharField(max_length=20, verbose_name='Acción')),
                ('campos_modificados', models.JSONField(default=dict, verbose_name='Campos modificados')),
                ('valores_anteriores', models.JSONField(default=dict, verbose_name='Valores anteriores')),
                ('valores_nuevos', models.JSONField(default=dict, verbose_name='Valores nuevos')),
                ('justificacion', models.TextField(blank=True, verbose_name='Justificación')),
                ('fecha_modificacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de modificación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Modificación',
                'verbose_name_plural': 'Registros de Modificaciones',
                'ordering': ['-fecha_modificacion'],
            },
        ),
        migrations.DeleteModel(
            name='InventarioAves',
        ),
        migrations.AddField(
            model_name='inventariohuevos',
            name='dias_stock',
            field=models.PositiveIntegerField(default=3, help_text='Número de días de stock mínimo a mantener', verbose_name='Días de stock'),
        ),
        migrations.AddField(
            model_name='inventariohuevos',
            name='factor_calculo',
            field=models.DecimalField(decimal_places=2, default=0.75, help_text='Factor multiplicador para calcular stock mínimo (ej: 0.75 = 75% de producción esperada)', max_digits=5, verbose_name='Factor de cálculo'),
        ),
        migrations.AddField(
            model_name='inventariohuevos',
            name='fecha_ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
    ]
