# Generated by Django 4.2.26 on 2026-02-16 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0010_alertasistema_registromodificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioAves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('detalle', models.CharField(help_text='Descripción del movimiento o estado', max_length=200, verbose_name='Detalle')),
                ('aves_inicio', models.PositiveIntegerField(default=0, verbose_name='Aves Inicio (Cría)')),
                ('pollitas_levante', models.PositiveIntegerField(default=0, verbose_name='Pollitas Levante')),
                ('aves_postura', models.PositiveIntegerField(default=0, verbose_name='Aves Postura')),
                ('aves_engorde', models.PositiveIntegerField(default=0, verbose_name='Aves Engorde')),
                ('reproductores', models.PositiveIntegerField(default=0, verbose_name='Reproductores')),
                ('compras', models.PositiveIntegerField(default=0, verbose_name='Compras')),
                ('nacimientos', models.PositiveIntegerField(default=0, verbose_name='Nacimientos')),
                ('ventas', models.PositiveIntegerField(default=0, verbose_name='Ventas')),
                ('mortalidad', models.PositiveIntegerField(default=0, verbose_name='Mortalidad')),
                ('autoconsumo', models.PositiveIntegerField(default=0, verbose_name='Autoconsumo')),
                ('descartes', models.PositiveIntegerField(default=0, verbose_name='Descartes')),
                ('total', models.PositiveIntegerField(default=0, editable=False, verbose_name='Total Aves')),
            ],
            options={
                'verbose_name': 'Inventario Permanente Aves',
                'verbose_name_plural': 'Inventarios Permanentes Aves',
                'ordering': ['-fecha'],
            },
        ),
    ]
