# Generated by Django 4.2.26 on 2026-02-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0012_seed_tipo_vacuna_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteaves',
            name='estado',
            field=models.CharField(default='levante', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='loteaves',
            name='linea_genetica',
            field=models.CharField(max_length=100, verbose_name='Línea genética'),
        ),
    ]
