# Generated by Django 4.2.26 on 2026-02-26 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aves', '0013_alter_loteaves_estado_alter_loteaves_linea_genetica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventarioaves',
            options={'ordering': ['-fecha'], 'verbose_name': 'Inventario de Aves', 'verbose_name_plural': 'Inventarios de Aves'},
        ),
        migrations.RemoveField(
            model_name='inventarioaves',
            name='autoconsumo',
        ),
        migrations.RemoveField(
            model_name='inventarioaves',
            name='compras',
        ),
        migrations.RemoveField(
            model_name='inventarioaves',
            name='descartes',
        ),
        migrations.RemoveField(
            model_name='inventarioaves',
            name='mortalidad',
        ),
        migrations.RemoveField(
            model_name='inventarioaves',
            name='nacimientos',
        ),
        migrations.RemoveField(
            model_name='inventarioaves',
            name='reproductores',
        ),
        migrations.RemoveField(
            model_name='inventarioaves',
            name='total',
        ),
        migrations.RemoveField(
            model_name='inventarioaves',
            name='ventas',
        ),
        migrations.AlterField(
            model_name='loteaves',
            name='estado',
            field=models.CharField(choices=[('levante', 'Pollas de Levante'), ('postura', 'En Postura'), ('finalizado', 'Finalizado')], default='levante', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='loteaves',
            name='linea_genetica',
            field=models.CharField(choices=[('hy_line_brown', 'Hy-Line Brown'), ('hy_line_white', 'Hy-Line White'), ('lohmann_brown', 'Lohmann Brown'), ('lohmann_white', 'Lohmann White'), ('isa_brown', 'ISA Brown'), ('isa_white', 'ISA White'), ('bovans_brown', 'Bovans Brown'), ('bovans_white', 'Bovans White'), ('dekalb_brown', 'Dekalb Brown'), ('dekalb_white', 'Dekalb White'), ('babcock_brown', 'Babcock Brown'), ('otra', 'Otra')], max_length=50, verbose_name='Línea genética'),
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=20, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completada', 'Completada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_limite', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Límite')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_aves', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['-created_at'],
            },
        ),
    ]
