# Generated by Django 4.2.26 on 2026-02-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0014_alter_inventarioaves_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoradiaria',
            name='imagen_huevos_rotos',
            field=models.ImageField(blank=True, help_text='Requerida si hay huevos rotos', null=True, upload_to='aves/huevos_rotos/', verbose_name='Evidencia de huevos rotos'),
        ),
    ]
