# Generated by Django 4.2.26 on 2026-03-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0015_bitacoradiaria_imagen_huevos_rotos'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoradiaria',
            name='firma_responsable',
            field=models.ImageField(blank=True, help_text='Foto de la firma del encargado', null=True, upload_to='aves/firmas/', verbose_name='Firma del responsable'),
        ),
    ]
