# Generated by Django 4.2.26 on 2026-03-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0016_bitacoradiaria_firma_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioaves',
            name='firma_responsable',
            field=models.ImageField(blank=True, help_text='Foto de la firma del encargado', null=True, upload_to='aves/firmas_inventario/', verbose_name='Firma del responsable'),
        ),
    ]
