# Generated by Django 4.2.26 on 2026-03-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0017_inventarioaves_firma_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoradiaria',
            name='descarte',
            field=models.PositiveIntegerField(default=0, verbose_name='Descarte'),
        ),
        migrations.AddField(
            model_name='bitacoradiaria',
            name='huevos_farfara',
            field=models.PositiveIntegerField(default=0, verbose_name='Huevos fárfara'),
        ),
        migrations.AddField(
            model_name='bitacoradiaria',
            name='huevos_sucios',
            field=models.PositiveIntegerField(default=0, verbose_name='Huevos sucios'),
        ),
        migrations.AddField(
            model_name='bitacoradiaria',
            name='produccion_jumbo',
            field=models.PositiveIntegerField(default=0, verbose_name='Producción Jumbo'),
        ),
    ]
