# Generated by Django 4.2.26 on 2026-03-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0018_bitacoradiaria_descarte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioaves',
            name='autoconsumo',
            field=models.PositiveIntegerField(default=0, verbose_name='Autoconsumo'),
        ),
        migrations.AddField(
            model_name='inventarioaves',
            name='compras',
            field=models.PositiveIntegerField(default=0, verbose_name='Compras'),
        ),
        migrations.AddField(
            model_name='inventarioaves',
            name='descartes',
            field=models.PositiveIntegerField(default=0, verbose_name='Descartes'),
        ),
        migrations.AddField(
            model_name='inventarioaves',
            name='mortalidad',
            field=models.PositiveIntegerField(default=0, verbose_name='Mortalidad'),
        ),
        migrations.AddField(
            model_name='inventarioaves',
            name='nacimientos',
            field=models.PositiveIntegerField(default=0, verbose_name='Nacimientos'),
        ),
        migrations.AddField(
            model_name='inventarioaves',
            name='reproductores',
            field=models.PositiveIntegerField(default=0, verbose_name='Reproductores'),
        ),
        migrations.AddField(
            model_name='inventarioaves',
            name='ventas',
            field=models.PositiveIntegerField(default=0, verbose_name='Ventas'),
        ),
    ]
