# Generated by Django 4.2.26 on 2026-02-09 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraActividadesConejos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('actividad', models.TextField()),
                ('responsable', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Bitácora Actividades Conejos',
                'verbose_name_plural': 'Bitácoras Actividades Conejos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ControlDestetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camada_numero', models.CharField(max_length=50)),
                ('numero_animales', models.IntegerField()),
                ('sexo', models.CharField(choices=[('H', 'Hembra'), ('M', 'Macho'), ('Mixto', 'Mixto')], max_length=10)),
                ('peso_promedio', models.DecimalField(decimal_places=3, help_text='Peso promedio en Kg/g', max_digits=6)),
                ('madre_numero', models.CharField(max_length=50)),
                ('padre_numero', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_destete', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Control Destete',
                'verbose_name_plural': 'Controles Destetes',
                'ordering': ['-fecha_destete'],
            },
        ),
        migrations.CreateModel(
            name='InventarioConejos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('detalle', models.CharField(help_text='Clasificación o detalle (ej. Parto Jaula #38)', max_length=200)),
                ('jaula', models.CharField(blank=True, max_length=50, null=True)),
                ('identificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('madre_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Madre #')),
                ('gazapos_vivos', models.IntegerField(default=0)),
                ('gazapos_muertos', models.IntegerField(default=0)),
                ('compra', models.IntegerField(default=0)),
                ('venta', models.IntegerField(default=0)),
                ('muerte', models.IntegerField(default=0)),
                ('macho_levante_ceba', models.IntegerField(default=0)),
                ('hembra_levante_ceba', models.IntegerField(default=0)),
                ('reproductores', models.IntegerField(default=0)),
                ('hembra_reemplazo', models.IntegerField(default=0)),
                ('hembra_no_lactando', models.IntegerField(default=0)),
                ('hembra_lactando', models.IntegerField(default=0)),
                ('gazapos', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Inventario Permanente Conejos',
                'verbose_name_plural': 'Inventarios Permanentes Conejos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LibroDiarioConejos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('parto_jaula', models.CharField(blank=True, max_length=50, null=True)),
                ('parto_vivos', models.IntegerField(default=0)),
                ('parto_muertos', models.IntegerField(default=0)),
                ('palpacion_jaula', models.CharField(blank=True, max_length=50, null=True)),
                ('palpacion_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('monta_jaula', models.CharField(blank=True, max_length=50, null=True)),
                ('monta_macho', models.CharField(blank=True, max_length=50, null=True)),
                ('destete_jaula', models.CharField(blank=True, max_length=50, null=True)),
                ('destete_cantidad_hembras', models.IntegerField(default=0)),
                ('destete_cantidad_machos', models.IntegerField(default=0)),
                ('destete_peso_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('muerte_jaula', models.CharField(blank=True, max_length=50, null=True)),
                ('muerte_levante_ceba', models.IntegerField(default=0)),
                ('muerte_reproductores', models.IntegerField(default=0)),
                ('venta_jaula', models.CharField(blank=True, max_length=50, null=True)),
                ('venta_levante_ceba', models.IntegerField(default=0)),
                ('venta_pie_cria', models.IntegerField(default=0)),
                ('tratamientos', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Libro Diario Conejos',
                'verbose_name_plural': 'Libros Diarios Conejos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAlimentoConejos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('unidad', models.CharField(default='Kg', max_length=50)),
                ('entrada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Registro Alimento Conejos',
                'verbose_name_plural': 'Registros Alimento Conejos',
                'ordering': ['-fecha'],
            },
        ),
    ]
