# Generated by Django 4.2.26 on 2026-02-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cunicultura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioConejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='Conejo en pie', max_length=100)),
                ('edad_dias', models.CharField(help_text='Rango de edad (ej. 35 a 42)', max_length=50)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Precio Conejo',
                'verbose_name_plural': 'Precios Conejos',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
