# Generated by Django 4.2.26 on 2026-02-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cunicultura', '0002_precioconejo'),
    ]

    operations = [
        migrations.AddField(
            model_name='librodiarioconejos',
            name='alimentacion_levante_ceba',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='librodiarioconejos',
            name='alimentacion_reproduccion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='librodiarioconejos',
            name='alimentacion_total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='librodiarioconejos',
            name='gazapera_poner_jaula',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Poner Jaula'),
        ),
        migrations.AddField(
            model_name='librodiarioconejos',
            name='gazapera_quitar_jaula',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Quitar Jaula'),
        ),
        migrations.AddField(
            model_name='librodiarioconejos',
            name='muerte_gazapos',
            field=models.IntegerField(default=0),
        ),
    ]
