# Generated by Django 4.2.26 on 2026-03-03 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cunicultura', '0003_librodiarioconejos_alimentacion_levante_ceba_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialInventarioConejos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar')], max_length=20)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('registro_id', models.IntegerField(blank=True, help_text='ID del registro original', null=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
                ('detalle_registro', models.CharField(blank=True, max_length=200, null=True)),
                ('datos_anteriores', models.TextField(blank=True, help_text='JSON con los datos del registro', null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial Inventario Conejos',
                'verbose_name_plural': 'Historiales Inventario Conejos',
                'ordering': ['-fecha_accion'],
            },
        ),
    ]
