# Generated by Django 4.2.26 on 2026-03-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cunicultura', '0004_historialinventarioconejos'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioconejos',
            name='firma_responsable',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/cunicultura/inventario/'),
        ),
    ]
