# Generated by Django 4.2.26 on 2026-03-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cunicultura', '0005_inventarioconejos_firma_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='librodiarioconejos',
            name='alimentacion_am',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Alimentación AM'),
        ),
        migrations.AddField(
            model_name='librodiarioconejos',
            name='alimentacion_pm',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Alimentación PM'),
        ),
    ]
