# Generated by Django 4.2.26 on 2026-03-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cunicultura', '0007_tareacunicultura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controldestetes',
            name='peso_promedio',
        ),
        migrations.RemoveField(
            model_name='controldestetes',
            name='sexo',
        ),
        migrations.AddField(
            model_name='controldestetes',
            name='hembras_cantidad',
            field=models.IntegerField(default=0, verbose_name='H'),
        ),
        migrations.AddField(
            model_name='controldestetes',
            name='hembras_peso_promedio',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Peso X H'),
        ),
        migrations.AddField(
            model_name='controldestetes',
            name='machos_cantidad',
            field=models.IntegerField(default=0, verbose_name='M'),
        ),
        migrations.AddField(
            model_name='controldestetes',
            name='machos_peso_promedio',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Peso X M'),
        ),
    ]
