# Generated by Django 4.2.26 on 2026-03-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cunicultura', '0008_remove_controldestetes_peso_promedio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanVacunacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_programada', models.DateField(verbose_name='Fecha programada')),
                ('nombre_vacuna', models.CharField(max_length=100, verbose_name='Nombre de la vacuna')),
                ('detalle', models.CharField(max_length=100, verbose_name='Detalle (Jaula/Lote)')),
                ('fecha_aplicada', models.DateField(blank=True, null=True, verbose_name='Fecha aplicada')),
                ('aplicada', models.BooleanField(default=False, verbose_name='Aplicada')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Plan de Vacunación',
                'verbose_name_plural': 'Planes de Vacunación',
                'ordering': ['fecha_programada'],
            },
        ),
    ]
