# Generated by Django 4.2.26 on 2025-11-27 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LotePorcino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('corral', models.CharField(max_length=100)),
                ('procedencia', models.CharField(blank=True, max_length=200)),
                ('numero_cerdos_inicial', models.PositiveIntegerField()),
                ('numero_cerdos_actual', models.PositiveIntegerField()),
                ('fecha_llegada', models.DateField()),
                ('peso_total_llegada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('peso_promedio_llegada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('engorde', 'Engorde'), ('vendido', 'Vendido'), ('cerrado', 'Cerrado')], default='activo', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Lote de Porcinos',
                'verbose_name_plural': 'Lotes de Porcinos',
                'ordering': ['-fecha_llegada'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraDiariaPorcinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha', models.DateField()),
                ('peso_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('consumo_alimento_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('animales_enfermos', models.PositiveIntegerField(default=0)),
                ('mortalidad', models.PositiveIntegerField(default=0)),
                ('tratamiento_aplicado', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='porcinos.loteporcino')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora Diaria Porcinos',
                'verbose_name_plural': 'Bitácoras Diarias Porcinos',
                'ordering': ['-fecha'],
            },
        ),
    ]
