# Generated by Django 4.2.25 on 2026-02-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('porcinos', '0002_alertaporcinos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlertaPorcinos',
        ),
    ]
