# Generated by Django 4.2.26 on 2026-03-04 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('porcinos', '0004_tareaporcinos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaPorcinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo_alerta', models.CharField(choices=[('mortalidad_alta', 'Mortalidad Alta'), ('consumo_anormal', 'Consumo Anormal'), ('peso_bajo', 'Peso Bajo'), ('vacuna_pendiente', 'Vacuna Pendiente')], max_length=30)),
                ('nivel', models.CharField(choices=[('critica', 'Crítica'), ('normal', 'Normal')], max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('corral_nombre', models.CharField(blank=True, max_length=100)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='porcinos.loteporcino')),
                ('usuario_destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_porcinos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Porcinos',
                'verbose_name_plural': 'Alertas de Porcinos',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
