# Generated by Django 4.2.26 on 2026-03-04 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('porcinos', '0005_alertaporcinos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalPorcino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('raza', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1)),
                ('etapa', models.CharField(choices=[('lechon', 'Lechón'), ('destete', 'Destete'), ('engorde', 'Engorde'), ('reemplazo', 'Reemplazo'), ('reproductor', 'Reproductor'), ('descarte', 'Descarte')], default='lechon', max_length=20)),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='porcinos/animales/')),
                ('notas', models.TextField(blank=True)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animales', to='porcinos.loteporcino')),
            ],
            options={
                'verbose_name': 'Animal Porcino',
                'verbose_name_plural': 'Animales Porcinos',
                'ordering': ['codigo'],
            },
        ),
    ]
