# Generated by Django 4.2.26 on 2026-03-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porcinos', '0006_animalporcino'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoradiariaporcinos',
            name='firma_encargado',
            field=models.ImageField(blank=True, null=True, upload_to='porcinos/firmas/'),
        ),
    ]
