# Generated by Django 4.2.26 on 2026-03-05 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('porcinos', '0007_bitacoradiariaporcinos_firma_encargado'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioPorcino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('detalle', models.CharField(blank=True, max_length=200)),
                ('madre', models.PositiveIntegerField(default=0)),
                ('reproductores', models.PositiveIntegerField(default=0)),
                ('hembras_reemplazo', models.PositiveIntegerField(default=0)),
                ('hembras_gestacion', models.PositiveIntegerField(default=0)),
                ('hembras_lactando', models.PositiveIntegerField(default=0)),
                ('lechones_lactando', models.PositiveIntegerField(default=0)),
                ('preiniciador', models.PositiveIntegerField(default=0)),
                ('levante_ceba', models.PositiveIntegerField(default=0)),
                ('descartes', models.PositiveIntegerField(default=0)),
                ('lechones_vivos', models.PositiveIntegerField(default=0)),
                ('lechones_muertos', models.PositiveIntegerField(default=0)),
                ('destetes', models.PositiveIntegerField(default=0)),
                ('compras', models.PositiveIntegerField(default=0)),
                ('ventas', models.PositiveIntegerField(default=0)),
                ('salidas', models.PositiveIntegerField(default=0)),
                ('muertes', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('firma_realizado', models.ImageField(blank=True, null=True, upload_to='porcinos/firmas/inventario/')),
                ('firma_revisado', models.ImageField(blank=True, null=True, upload_to='porcinos/firmas/inventario/')),
                ('firma_aprobado', models.ImageField(blank=True, null=True, upload_to='porcinos/firmas/inventario/')),
                ('realizado_por', models.CharField(blank=True, max_length=100)),
                ('revisado_por', models.CharField(blank=True, max_length=100)),
                ('aprobado_por', models.CharField(blank=True, max_length=100)),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventario Porcino',
                'verbose_name_plural': 'Inventarios Porcinos',
                'ordering': ['-fecha'],
            },
        ),
    ]
