# Generated by Django 4.2.29 on 2026-03-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('superusuario', 'Superusuario'), ('admin_aves', 'Administrador de Aves'), ('admin_bovinos', 'Administrador de Bovinos'), ('admin_equinos', 'Administrador de Equinos'), ('admin_porcinos', 'Administrador de Porcinos'), ('admin_ovinos', 'Administrador de Ovinos'), ('admin_caprinos', 'Administrador de Caprinos'), ('admin_cunicola', 'Administrador de Cunicola'), ('veterinario', 'Veterinario'), ('punto_blanco', 'Punto Blanco (Venta)'), ('solo_vista', 'Solo Vista')], max_length=20, verbose_name='Rol'),
        ),
    ]
