# Generated by Django 4.2.24 on 2025-09-05 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('produccion', 'Producción'), ('inventario', 'Inventario'), ('financiero', 'Financiero'), ('salud', 'Salud Animal'), ('general', 'General')], max_length=50)),
                ('plantilla_html', models.TextField(blank=True)),
                ('campos_disponibles', models.JSONField(default=dict, help_text='Campos disponibles para el reporte')),
            ],
            options={
                'verbose_name': 'Tipo de Reporte',
                'verbose_name_plural': 'Tipos de Reportes',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReporteProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('frecuencia', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral')], max_length=20)),
                ('hora_ejecucion', models.TimeField()),
                ('dia_semana', models.IntegerField(blank=True, help_text='1=Lunes, 7=Domingo', null=True)),
                ('dia_mes', models.IntegerField(blank=True, help_text='Día del mes (1-31)', null=True)),
                ('parametros', models.JSONField(default=dict)),
                ('formato_salida', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('enviar_email', models.BooleanField(default=False)),
                ('emails_destino', models.JSONField(default=list, help_text='Lista de emails para envío')),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('proxima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('tipo_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.tiporeporte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Programado',
                'verbose_name_plural': 'Reportes Programados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML')], max_length=10)),
                ('parametros', models.JSONField(default=dict, help_text='Parámetros usados para generar el reporte')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('estado', models.CharField(choices=[('generando', 'Generando'), ('completado', 'Completado'), ('error', 'Error')], default='generando', max_length=20)),
                ('mensaje_error', models.TextField(blank=True)),
                ('tipo_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportes.tiporeporte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
