# Generated by Django 4.2.26 on 2025-11-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportegenerado',
            name='formato',
            field=models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML')], max_length=10),
        ),
        migrations.AlterField(
            model_name='reporteprogramado',
            name='formato_salida',
            field=models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV')], default='excel', max_length=10),
        ),
    ]
