# Generated by Django 4.2.25 on 2026-02-27 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('raza', models.CharField(blank=True, max_length=100, verbose_name='Raza')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1, verbose_name='Sexo')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='Color/Pelaje')),
                ('microchip', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Microchip')),
                ('padre', models.CharField(blank=True, max_length=100, verbose_name='Padre')),
                ('madre', models.CharField(blank=True, max_length=100, verbose_name='Madre')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vendido', 'Vendido'), ('fallecido', 'Fallecido')], default='activo', max_length=20, verbose_name='Estado')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equinos/', verbose_name='Foto')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Equino',
                'verbose_name_plural': 'Equinos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TratamientoSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('vacuna', 'Vacunación'), ('vermifugo', 'Vermífugo'), ('herraje', 'Herraje/Cascos'), ('odontologia', 'Odontología'), ('veterinario', 'Consulta Veterinaria'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de tratamiento')),
                ('producto', models.CharField(blank=True, max_length=100, verbose_name='Producto/Medicamento')),
                ('dosis', models.CharField(blank=True, max_length=100, verbose_name='Dosis')),
                ('veterinario', models.CharField(blank=True, max_length=100, verbose_name='Veterinario/Responsable')),
                ('proxima_fecha', models.DateField(blank=True, null=True, verbose_name='Próxima aplicación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('equino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='equinos.equino')),
            ],
            options={
                'verbose_name': 'Tratamiento y Salud',
                'verbose_name_plural': 'Tratamientos y Salud',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('actividad', models.CharField(max_length=200, verbose_name='Actividad/Entrenamiento')),
                ('tiempo_minutos', models.PositiveIntegerField(default=0, verbose_name='Tiempo (minutos)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('equino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_diarios', to='equinos.equino')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Registro Diario',
                'verbose_name_plural': 'Registros Diarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('medica', 'Médica'), ('comportamiento', 'Comportamiento'), ('movimiento', 'Movimiento/Traslado'), ('reproductiva', 'Reproductiva'), ('otra', 'Otra')], max_length=20, verbose_name='Tipo de novedad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('equino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novedades', to='equinos.equino')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Novedad',
                'verbose_name_plural': 'Novedades',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inicio')),
                ('tipo_alimento', models.CharField(max_length=100, verbose_name='Tipo de alimento')),
                ('cantidad_kg', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cantidad (kg/día)')),
                ('frecuencia', models.CharField(default='Diario', max_length=100, verbose_name='Frecuencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('equino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentacion', to='equinos.equino')),
            ],
            options={
                'verbose_name': 'Alimentación',
                'verbose_name_plural': 'Alimentación',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
