# Generated by Django 4.2.26 on 2026-03-05 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equinos', '0003_alter_registrodiario_options_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodiario',
            name='actividad',
            field=models.CharField(max_length=200, verbose_name='Título/Actividad'),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='equino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_diarios', to='equinos.equino'),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Contexto del día'),
        ),
        migrations.AlterField(
            model_name='registrodiario',
            name='tiempo_minutos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Tiempo (minutos)'),
        ),
    ]
