# Generated by Django 4.2.26 on 2026-03-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equinos', '0004_alter_registrodiario_actividad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tipo', models.CharField(choices=[('alimentacion', 'Alimentación'), ('formulas', 'Fórmulas y Mezclas'), ('cronograma', 'Cronograma Semanal'), ('general', 'General')], default='general', max_length=20, verbose_name='Tipo de Tablero')),
                ('contenido', models.TextField(blank=True, help_text='Información detallada del tablero', verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Tablero Informativo',
                'verbose_name_plural': 'Tableros Informativos',
                'ordering': ['tipo', 'titulo'],
            },
        ),
    ]
