# Generated by Django 4.2.26 on 2026-03-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equinos', '0005_tablero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tablero',
        ),
    ]
