# Generated by Django 4.2.24 on 2025-10-08 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aves', '0004_alter_alertasistema_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPuntoBlanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('nombre_punto', models.CharField(default='Punto Blanco', max_length=100, verbose_name='Nombre del Punto')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('margen_ganancia_default', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Margen de Ganancia Default (%)')),
                ('hora_apertura', models.TimeField(default='08:00', verbose_name='Hora de Apertura')),
                ('hora_cierre', models.TimeField(default='18:00', verbose_name='Hora de Cierre')),
                ('costo_domicilio', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Costo de Domicilio')),
                ('radio_entrega_km', models.PositiveIntegerField(default=10, verbose_name='Radio de Entrega (km)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Configuración Punto Blanco',
                'verbose_name_plural': 'Configuraciones Punto Blanco',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('numero_pedido', models.CharField(max_length=20, unique=True, verbose_name='Número de Pedido')),
                ('cliente_nombre', models.CharField(max_length=100, verbose_name='Nombre del Cliente')),
                ('cliente_telefono', models.CharField(max_length=15, verbose_name='Teléfono del Cliente')),
                ('cliente_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del Cliente')),
                ('cliente_direccion', models.TextField(blank=True, verbose_name='Dirección del Cliente')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_preparacion', 'En Preparación'), ('listo', 'Listo para Entrega'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('tipo_entrega', models.CharField(choices=[('recoger', 'Recoger en Punto'), ('domicilio', 'Entrega a Domicilio')], default='recoger', max_length=20, verbose_name='Tipo de Entrega')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Pedido')),
                ('fecha_entrega_estimada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega Estimada')),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Entrega Real')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('usuario_punto_blanco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_punto_blanco', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Punto Blanco')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('inventario_huevos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aves.inventariohuevos', verbose_name='Producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='punto_blanco.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
                'unique_together': {('pedido', 'inventario_huevos')},
            },
        ),
    ]
